name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        always-auth: no
        node-version: >=13.9
        architecture: true
        check-latest: true
    
